// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICl4Ut4UgzahHNJC3rAaM3N6LNxnZ7M4',
    appId: '1:203026445551:web:938175d921edf5072d571a',
    messagingSenderId: '203026445551',
    projectId: 'flutter-learnings-57937',
    authDomain: 'flutter-learnings-57937.firebaseapp.com',
    storageBucket: 'flutter-learnings-57937.firebasestorage.app',
    measurementId: 'G-ZP0W2KTDSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9UHsL5xPS96FyZ4wPhiNCc1auB8940Io',
    appId: '1:203026445551:android:8b014f0aa8413db92d571a',
    messagingSenderId: '203026445551',
    projectId: 'flutter-learnings-57937',
    storageBucket: 'flutter-learnings-57937.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj_Y_d0xQoMrRYH8PtMgqKdIMzYqGhBIs',
    appId: '1:203026445551:ios:83afad194a4878e82d571a',
    messagingSenderId: '203026445551',
    projectId: 'flutter-learnings-57937',
    storageBucket: 'flutter-learnings-57937.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearnings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj_Y_d0xQoMrRYH8PtMgqKdIMzYqGhBIs',
    appId: '1:203026445551:ios:83afad194a4878e82d571a',
    messagingSenderId: '203026445551',
    projectId: 'flutter-learnings-57937',
    storageBucket: 'flutter-learnings-57937.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearnings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBICl4Ut4UgzahHNJC3rAaM3N6LNxnZ7M4',
    appId: '1:203026445551:web:eedf73317756b1bd2d571a',
    messagingSenderId: '203026445551',
    projectId: 'flutter-learnings-57937',
    authDomain: 'flutter-learnings-57937.firebaseapp.com',
    storageBucket: 'flutter-learnings-57937.firebasestorage.app',
    measurementId: 'G-FVY8N9DWBK',
  );
}
